# Generated by Django 4.2.6 on 2024-01-22 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_manager', '0020_alter_pool_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='range',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_range', message='Enter a valid range.', regex='^((\\s*\\d+\\s*)(-\\s*\\d+\\s*)?(,)?)+$')]),
        ),
    ]
