class Application:
    def __init__(self) -> None: ...
    @property
    def initialized(self): ...
    @property
    def license_verifier(self): ...
    @property
    def license(self): ...
    @property
    def admin_root(self): ...
    @property
    def working_directory(self): ...
    def run(self) -> None: ...
