# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.property_records200_response_inner_property_taxes2021 import PropertyRecords200ResponseInnerPropertyTaxes2021

class TestPropertyRecords200ResponseInnerPropertyTaxes2021(unittest.TestCase):
    """PropertyRecords200ResponseInnerPropertyTaxes2021 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyRecords200ResponseInnerPropertyTaxes2021:
        """Test PropertyRecords200ResponseInnerPropertyTaxes2021
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyRecords200ResponseInnerPropertyTaxes2021`
        """
        model = PropertyRecords200ResponseInnerPropertyTaxes2021()
        if include_optional:
            return PropertyRecords200ResponseInnerPropertyTaxes2021(
                total = 3455
            )
        else:
            return PropertyRecords200ResponseInnerPropertyTaxes2021(
        )
        """

    def testPropertyRecords200ResponseInnerPropertyTaxes2021(self):
        """Test PropertyRecords200ResponseInnerPropertyTaxes2021"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
