# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from ..common.user_info import UserInfo
from ..common.application_info import ApplicationInfo
import typing_extensions
from ...core.serialization import FieldMetadata
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class Login(UniversalBaseModel):
    user: UserInfo
    application: ApplicationInfo
    count: int
    time_frame: typing_extensions.Annotated[int, FieldMetadata(alias="timeFrame")]
    last: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
