# This file was auto-generated by Fern from our API Definition.

import typing
from .video_bots_page_request_messages_item_content_item import VideoBotsPageRequestMessagesItemContentItem

VideoBotsPageRequestMessagesItemContent = typing.Union[str, typing.List[VideoBotsPageRequestMessagesItemContentItem]]
