# coding: utf-8

"""
    CCT Customer Service Requests

    API for interacting with City of Cape Town's eServices

    The version of the OpenAPI document: 2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from coct_sr_api_client.models.request_attributes_lookup_schema import RequestAttributesLookupSchema

class TestRequestAttributesLookupSchema(unittest.TestCase):
    """RequestAttributesLookupSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestAttributesLookupSchema:
        """Test RequestAttributesLookupSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestAttributesLookupSchema`
        """
        model = RequestAttributesLookupSchema()
        if include_optional:
            return RequestAttributesLookupSchema(
                reference_number = '2101825',
                type = '1001',
                subtype = '1002',
                description = 'Animal carcass removal - Whale',
                status = 'Closed',
                message = ' Please collect the whale carcass from Muizenberg beach before the wind direction changes. 28.11.2014 11:20:13 Gareth Dohne (SC_GD1) The carcass Please collect the whale carcass from Muizenberg beach has been successfully removed from the beach and the surrounding area cleaned up.',
                time_created = '10:08:59',
                date_created = '28.11.2014'
            )
        else:
            return RequestAttributesLookupSchema(
                reference_number = '2101825',
                type = '1001',
                subtype = '1002',
                description = 'Animal carcass removal - Whale',
                status = 'Closed',
                message = ' Please collect the whale carcass from Muizenberg beach before the wind direction changes. 28.11.2014 11:20:13 Gareth Dohne (SC_GD1) The carcass Please collect the whale carcass from Muizenberg beach has been successfully removed from the beach and the surrounding area cleaned up.',
                time_created = '10:08:59',
                date_created = '28.11.2014',
        )
        """

    def testRequestAttributesLookupSchema(self):
        """Test RequestAttributesLookupSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
