# Generated by Django 4.2.7 on 2023-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_company_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='outsourced',
            field=models.JSONField(default={}),
        ),
    ]
