{
 "title": "ClusterDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(cluster_read_io{cluster_id=${__user.id}})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster_size_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_size_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_size_free{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_size_used{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_prov",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_size_prov{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_prov_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cluster_size_prov_util{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cluster_size_util{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "cluster_write_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_write_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "cluster_write_bytes_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_write_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cluster_write_latency_ps{cluster=\"$Cluster\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_write_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "cluster_write_io{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "cluster_write_io_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_wite_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 23 },
   "targets": [
    {
     "expr": "cluster_write_latency_ticks{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "cluster_read_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_read_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_read_bytes_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_read_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cluster_read_latency_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_read_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "cluster_read_io{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 39 },
   "targets": [
    {
     "expr": "cluster_read_io_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_read_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 39 },
   "targets": [
    {
     "expr": "cluster_read_latency_ticks{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "unmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "cluster_unmap_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "cluster_unmap_latency_ticks{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_bytes_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_unmap_bytes_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cluster_unmap_latency_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_io_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "cluster_unmap_io_ps{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 54 },
   "targets": [
    {
     "expr": "cluster_unmap_io{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_unmap_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}