
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-10T11:22:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9100d6d7f1907f15b1cfdedaa88716befb9ee3c7",
 "version": "1.30.0.post0.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
