
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-11T12:57:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eec954b8b28e3a2c1a814d20090ad51b29b03e01",
 "version": "0.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
