from pycsp3.problems.data.parsing import *

data['horizon'] = number_in(line())
nWorkers = number_in(next_line())
nProducts = number_in(next_line())
nProductTypes = number_in(next_line())
nStations = number_in(next_line())
data['releaseTimeW'] = numbers_in(next_line())
data['workerInitial'] = numbers_in(next_line())
data['currentStation'] = numbers_in(next_line())
data['currentStep'] = numbers_in(next_line())
data['currentBuffer'] = numbers_in(next_line())
data['releaseTime'] = numbers_in(next_line())
data['productType'] = numbers_in(next_line())
assert nWorkers == len(data['releaseTimeW']) == len(data['workerInitial'])
assert nProducts == len(data['currentStation']) == len(data['currentStep']) == len(data['currentBuffer']) == len(data['releaseTime'])
next_line()
data['production'] = split_with_rows_of_size(numbers_in(next_line())[3:], nStations)
next_line()
data['worksteps'] = split_with_rows_of_size(numbers_in(next_line())[3:], nStations)
next_line()
data['setup'] = split_with_rows_of_size(numbers_in(next_line())[3:], nStations)
next_line()
data['takedown'] = split_with_rows_of_size(numbers_in(next_line())[3:], nStations)
next_line()
data['workerMovement'] = split_with_rows_of_size(numbers_in(next_line())[3:], nStations)
assert nProductTypes == len(data['production']) == len(data['worksteps']) == len(data['setup']) == len(data['takedown'])
assert nProductTypes == len(data['production'])
