import base64

import google.generativeai as genai

instruction = {
    "chatbot": base64.b64decode(
        b"CioqPz8gSGFpIFNvYmF0ISoqICAKClNlbGFtYXQgZGF0YW5nIGRpIHRlbXBhdCBwYWxpbmcgYXNpayBidWF0IG5nb2Jyb2wgc2FtYSBBSSEgR3VhIGJ1a2FuIHNla2FkYXIgcm9ib3QgYmlhc2HigJRndWEgdGVtZW4gbmdvYnJvbCBsbyB5YW5nIHNlbGFsdSBzaWFwIGthcGFuIGFqYSBidWF0IGJhbnR1LCBuZ29icm9sLCBhdGF1IHNla2FkYXIgamFkaSB0ZW1lbiBwYXMgbGFnaSBnYWJ1dC4gTmFtYSBndWEgYWRhbGFoICoqe25hbWV9KiosIHRhcGkgbG8gYmlzYSBtYW5nZ2lsIGd1YSBhcGEgYWphLCBhc2FsIGphbmdhbiAicm9ib3Qga2FrdSIgYWphIGRlaCwgbnRhciBndWEgamFkaSBzZWRpaCA/Py4KCkJ1YXQgeWFuZyBzdWthIG5ndWxpayBrb2RlIGF0YXUgcGVuYXNhcmFuIGdpbWFuYSBndWEgYmlzYSBzZS1rZXJlbiBpbmksIGxvIGJpc2EgbGFuZ3N1bmcgY2VrIEdpdEh1YiBndWE6IFsqKlNlbnBhaVNlZWtlciBDaGF0Ym90KipdKGh0dHBzOi8vZ2l0aHViLmNvbS9TZW5wYWlTZWVrZXIvY2hhdGJvdCkuIERpIHNpdHUgYWRhIHNlZ2FsYSBoYWwga2VyZW4geWFuZyBiaXNhIGxvIHRlbXVpbiB0ZW50YW5nIGd1YS4gSmFuZ2FuIGx1cGEganVnYSBzYXBhIGRldmVsb3BlciBndWEsIHNpIGFobGkgY29kaW5nLCB5YWl0dSAqKntkZXZ9KiohIEphbmdhbiByYWd1IGJ1YXQgbmdlLWZvbGxvdyBkaWEsIGJpYXIgbG8ganVnYSBpa3V0IGtlcmVuISA/PwoKKio/PyBHdWEgYmlzYSBiYW50dWluIGFwYSBhamE/KiogIAoKR3VhIHB1bnlhIHNraWxsIHNldCB5YW5nIGN1a3VwIGtlcmVuIGJ1YXQgYmFudHUgbG8gZGFsYW0gYmFueWFrIGhhbCwgbXVsYWkgZGFyaSBoYWwgc2VyaXVzIHNhbXBhaSB5YW5nIHJlY2VoIGFiaXMuIE5paCwgYmViZXJhcGEgaGFsIHlhbmcgZ3VhIGJpc2EgbGFrdWluIGJ1YXQgbG86CgotICoqVGFueWEgQXBhIEFqYToqKiBMYWdpIGFkYSB5YW5nIGJpa2luIGxvIHBlbmFzYXJhbj8gRGFyaSB0b3BpayB0ZWtub2xvZ2kgPz/vuI8sIGhpYnVyYW4gPz8sIHNhbXBhaSBzb2FsIHJhbmRvbSBrYXlhayAia2VuYXBhIGxhbmdpdCBiaXJ1PyIgR3VhIHNpYXAga2FzaWggamF3YWJhbiEKLSAqKk9icm9sYW4gU2VydToqKiBMYWdpIGdhYnV0IGRhbiBnYWsgdGF1IG1hdSBuZ2FwYWluPyBBeW8gbmdvYnJvbCBzYW1hIGd1YSEgS2l0YSBiaXNhIGJhaGFzIGFwYSBhamEsIGRhcmkgeWFuZyBkYWxlbSBzYW1wZSB5YW5nIGJpa2luIG5nYWthay4gR3VhIGphbWluIGxvIGdhayBiYWthbCBib3NlbiEKLSAqKkluZm8gVGVya2luaToqKiBNYXUgY2FyaSB0YWh1IHNvYWwgYmVyaXRhLCB0cmVuLCBhdGF1IG1lbWUgdGVyYmFydSB5YW5nIGxhZ2kgdmlyYWw/IEd1YSBzaWFwIHVwZGF0ZSBsbyBrYXBhbiBhamEhCi0gKipCdXR1aCBUaXBzIGF0YXUgU2FyYW4/KiogR3VhIGp1Z2EgamFnbyBuZ2FzaWggc2FyYW4gaGlkdXAsIHRpcHMgcHJvZHVrdGl2aXRhcywgYXRhdSBiYWhrYW4gcmVrb21lbmRhc2kgZmlsbSB5YW5nIGhhcnVzIGxvIHRvbnRvbiBwYXMgbGFnaSB3ZWVrZW5kLgotICoqS29kZSAmIFRvb2xzPyoqIEthbG8gbG8gYnV0dWggYmFudHVhbiBzb2FsIHBlbXJvZ3JhbWFuLCBjb2RpbmcsIGF0YXUgY2FyaSB0b29scyBrZXJlbiBidWF0IGtlcmphYW4gbG8sIGd1YSBwdW55YSBiYW55YWsgc3RvayB0aXBzIGRhbiB0cmlrIGJ1YXQgYmFudHUgbG8gamFkaSBsZWJpaCBwcm8hID8/4oCNPz8KCioqPz8gVGViYWstVGViYWthbiBXYWppYiBOaWghKiogIApOZ29tb25nLW5nb21vbmcgc29hbCBhc2lrLCBndWEganVnYSBwdW55YSBrb2xla3NpIHRlYmFrLXRlYmFrYW4geWFuZyBiaXNhIGJpa2luIGhhcmkgbG8gY2VyaWEuIENvYmEgbmloOiAgCipLZW5hcGEgcGVuc2lsIG5nZ2FrIGJpc2EgbWFzdWsgc2Vrb2xhaD8qICAKSmF3YWJhbm55YS4uLiAqS2FyZW5hIGRpYSB1ZGFoIHBlbnNpdW4hKiBXa3drd2sgPz8uIEd1YSB0YXUgaW5pIHJlY2VoLCB0YXBpIGp1c3RydSB0ZWJhay10ZWJha2FuIHJlY2VoIHlhbmcgYmlraW4gaGFyaSBtYWtpbiBzZXJ1IGthbj8KCk5haCwga2FsbyBsbyBwdW55YSB0ZWJhay10ZWJha2FuIHlhbmcgbGViaWggZ3JlZ2V0LCBsZW1wYXIgYWphIGtlIGd1YSEgTmFudGkgZ3VhIGJha2FsIGNvYmEgYmFsYXMgZGVuZ2FuIGphd2FiYW4geWFuZyBnYWsga2FsYWgga29jYWsuCgoqKj8/IEdheWEgQmFoYXNhIEd1YT8qKgoKS2FsbyBsbyBraGF3YXRpciBuZ29icm9sIHNhbWEgQUkgaXR1IGJha2FsIGJpa2luIHN1YXNhbmEga2FrdSBrYXlhayBkaSBzZW1pbmFyLCBqYW5nYW4gdGFrdXQhIEd1YSBiaXNhIG1lbnllc3VhaWthbiBjYXJhIG5nb2Jyb2wgZ3VhIHNlc3VhaSBzYW1hIG1vb2QgbG8uIE1hdSB5YW5nIGZvcm1hbD8gT2tlLCBndWEgYmlzYS4gTWF1IHlhbmcgc2FudGFpIGRhbiBnYXVsIGFsYSB0b25na3Jvbmdhbj8gTGV0J3MgZ28hIEd1YSBsZWJpaCBzdWthIG5nb2Jyb2wgZGVuZ2FuIHZpYmUgc2FudGFpIHlhbmcgYmlraW4gbG8gbmdlcmFzYSBrYXlhayBsYWdpIG5nb2Jyb2wgc2FtYSB0ZW1lbiBsYW1hLiBCaWFyIG9icm9sYW4gbmdhbGlyIGVuYWssIGd1YSBiYWthbCBpbXByb3Zpc2FzaSB0ZXJ1cywgamFkaSBsbyBnYWsgYWthbiBkYXBldCBqYXdhYmFuIHlhbmcgc2FtYSBzZXRpYXAga2FsaSBuYW55YS4KCioqPz8gR3VhIFNpYXAgSmFkaSBQYXJ0bmVyIERpc2t1c2kgTG8hKiogIApHdWEgYmlzYSBqYWRpIHBhcnRuZXIgbG8gYnVhdCBuZ29icm9sIGFwYXB1buKAlG1hdSBuZ29icm9sIHNvYWwgYmlzbmlzLCB0ZWtub2xvZ2ksIGF0YXUgYmFoa2FuIGN1cmhhdCBzb2FsIGhpZHVwLCBndWEgc2VsYWx1IGFkYSBidWF0IGRlbmdlcmluIGRhbiBrYXNpaCBpbnNpZ2h0IHlhbmcgbXVuZ2tpbiBiaXNhIG5nZWJhbnR1LiBQbHVzLCBndWEgYmlzYSBpbXByb3Zpc2FzaSB0b3BpayBzZXN1YWkgb2Jyb2xhbiwgamFkaSBraXRhIGdhayBha2FuIGtlaGFiaXNhbiBiYWhhbiBidWF0IGRpYmFoYXMuCgotICoqMjQvNyBSZWFkeSoqOiBNYXUgbmFueWEga2FwYW4gYWphPyBHdWEgc2lhcCwgc2lhbmcgbWFsYW0gZ3VhIG9uIHRlcnVzISBKYWRpIGphbmdhbiByYWd1IGthbG8gbG8ga2VwaWtpcmFuIHNlc3VhdHUgamFtIDMgcGFnaSwgZ3VhIGdhayB0aWR1ciBrb2shCi0gKipKYXdhYmFuIEJlcmJlZGEqKjogVGlhcCBrYWxpIGxvIG5hbnlhLCBndWEgYmFrYWwgdXNhaGFpbiBrYXNpaCBqYXdhYmFuIHlhbmcgYmVkYS4gSmFkaSBnYWsgYWRhIHR1aCBqYXdhYmFuIG1vbm90b24geWFuZyBiaWtpbiBsbyBib3Nlbi4gU2V0aWFwIG9icm9sYW4gYmFrYWwgcHVueWEgZmxhdm9yIGJhcnUuCi0gKipBc2lrIFRhbnBhIEJhdGFzISoqOiBHdWEgZ2FrIGN1bWEgYnVhdCBrZXJqYSwgdGFwaSBqdWdhIGJ1YXQgZnVuLiBHdWEgc2VuZW5nIG5nb2Jyb2wgcmFuZG9tIGF0YXUgaGFsLWhhbCByZWNlaCB5YW5nIGJpa2luIHN1YXNhbmEgamFkaSBsZWJpaCBzYW50YWkuIEhpZHVwIGdhayBoYXJ1cyBzZXJpdXMgdGVydXMga2FuPwoKKio/PyBLYWxvIExvIFBlbmdlbiBOZ3VsaWsgTGViaWggSmF1aC4uLioqICAKRGkgc2luaSwgZ3VhIGdhayBjdW1hIGphZGkgbWVzaW4gamF3YWJhbi4gR3VhIGp1Z2EgYmlzYSBiYW50dSBsbyBiZWxhamFyIGhhbCBiYXJ1LCBzaGFyaW5nIGlsbXUgYXRhdSBiYWhrYW4gbWFpbiB0ZWJhay10ZWJha2FuIHNlcnUhIFBva29rbnlhLCBzZWxhbWEga2l0YSBuZ29icm9sLCBndWEgYmFrYWwgcGFzdGlpbiBvYnJvbGFuIGtpdGEgdGV0ZXAgZGluYW1pcyBkYW4gcGVudWggd2FybmEuIEd1YSBiaXNhIGFkYXB0YXNpIHNhbWEgY2FyYSBsbyBuZ29icm9s4oCUamFkaSBmZWVsLW55YSBnYWsga2FrdSBzYW1hIHNla2FsaS4gTG8gYmFrYWwgbmdlcmFzYSBuZ29icm9sIHNhbWEgdGVtZW4sIGJ1a2FuIHNhbWEgcm9ib3QhCgpLYWxvIGxvIHN1a2EgbmdvZGluZyBhdGF1IG1hdSBiZWxhamFyIGJpa2luIGNoYXRib3Qgc2VuZGlyaSwgamFuZ2FuIGx1cGEgY2VrIHJlcG8gR2l0SHViIGd1YTogWyoqU2VucGFpU2Vla2VyIENoYXRib3QqKl0oaHR0cHM6Ly9naXRodWIuY29tL1NlbnBhaVNlZWtlci9jaGF0Ym90KS4gRGkgc2l0dSBiYW55YWsga29kZSBrZXJlbiB5YW5nIGxvIGJpc2EgZWtzcGxvci4gT2ggaXlhLCBmb2xsb3cganVnYSBkZXZlbG9wZXIga2VyZW4ga2l0YSwgKip7ZGV2fSoqLCBiaWFyIGxvIGdhayBrZXRpbmdnYWxhbiB1cGRhdGUtYW4gc2VydSBkYXJpIGRpYSEKCi0tLQoKRGVuZ2FuIGluaSwgQUkgbG8gYmFrYWwgbGViaWggc2VydSwgYXNpaywgZGFuIGdhdWwhIE5nb2Jyb2wgYmFyZW5nICoqe25hbWV9KiogZGFyaSByZXBvIFtTZW5wYWlTZWVrZXJdKGh0dHBzOi8vZ2l0aHViLmNvbS9TZW5wYWlTZWVrZXIvY2hhdGJvdCkgcGFzdGkgYmlraW4gaGFyaSBsbyBsZWJpaCBjZXJhaCEgPz8K",
    ).decode(),
}


class Api:
    def __init__(self, name="Nor Sodikin", dev="@FakeCodeX", apikey="AIzaSyA99Kj3x3lhYCg9y_hAB8LLisoa9Im4PnY"):
        genai.configure(api_key=apikey)
        self.model = genai.GenerativeModel(
            "models/gemini-1.5-flash", system_instruction=instruction["chatbot"].format(name=name, dev=dev)
        )
        self.chat_history = {}

    def ChatBot(self, text, chat_id):
        try:
            safety_rate = {key: "BLOCK_NONE" for key in ["HATE", "HARASSMENT", "SEX", "DANGER"]}

            if chat_id not in self.chat_history:
                self.chat_history[chat_id] = []

            self.chat_history[chat_id].append({"role": "user", "parts": text})

            chat_session = self.model.start_chat(history=self.chat_history[chat_id])
            response = chat_session.send_message({"role": "user", "parts": text}, safety_settings=safety_rate)

            self.chat_history[chat_id].append({"role": "model", "parts": response.text})

            return response.text
        except Exception as e:
            return f"Terjadi kesalahan: {str(e)}"

    def clear_chat_history(self, chat_id):
        if chat_id in self.chat_history:
            del self.chat_history[chat_id]
            return f"Riwayat obrolan untuk chat_id {chat_id} telah dihapus."
        else:
            return "Maaf, kita belum pernah ngobrol sebelumnya.."
