key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIPlyCHd9g7xUfCSjEZiEVuQzYHTwHyQS1ph6IJeuWp0loAoGCCqGSM49
AwEHoUQDQgAEbzihcA0pY7m4q5+x+5MEka1HNMOzYuotBRKZsuNbIAhQttVpSH59
WOEQ8otbmNwApn97Rzo8Wc2Hwd1Couc7nA==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6DCCAY8CFAqUEaN/XA35JcqUvcOv6ACavBaaMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNDA5MDkwMzExMTBaFw0zNDA5MDcwMzEx
MTBaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABG84oXANKWO5uKufsfuTBJGtRzTDs2LqLQUSmbLjWyAIULbVaUh+fVjh
EPKLW5jcAKZ/e0c6PFnNh8HdQqLnO5wwCgYIKoZIzj0EAwIDRwAwRAIgTW8rYznR
C0HtopDFIDXfYsAosEaVbFNYgUAFhEJb85ACIC+Tt5Q6HldwlzxeiTjqLJgiJcQX
Gn7eTXHDpDm24QA4
-----END CERTIFICATE-----
"""