
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-11T08:37:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e332fa9b589e70ff3171d724fcc381c556631eb4",
 "version": "1.1.1.post0.dev78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
