#!/bin/bash

dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_53705-v03.epos" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R18_53705-v03.rng" "eln_data_apm.yaml" "apm.oasis.specific.yaml" --reader apm --nxdl NXapm --reader apm --nxdl NXapm --output=debug.aus_sydney_breen_1.nxs 1>stdout.debug.aus_sydney_breen_1.txt 2>stderr.debug.aus_sydney_breen_1.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ErMnO_pole.pos" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/ErMnO.env" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.nor_trondheim_hatzeglou_0.nxs 1>stdout.debug.nor_trondheim_hatzeglou_0.txt 2>stderr.debug.nor_trondheim_hatzeglou_0.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5006_29110_Top_Level_ROI.apt" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R5006_29110_Top_Level_ROI.RRNG" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.ger_duesseldorf_antonov_0.nxs 1>stdout.debug.ger_duesseldorf_antonov_0.txt 2>stderr.debug.ger_duesseldorf_antonov_0.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R87_02935-v03.epos" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R87_02935-v03.rrng" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.ger_duesseldorf_antonov_1.nxs 1>stdout.debug.ger_duesseldorf_antonov_1.txt 2>stderr.debug.ger_duesseldorf_antonov_1.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R31_11381-v02.ato" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Ceria_11553.rrng" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.usa_richland_kruska_0.nxs 1>stdout.debug.usa_richland_kruska_0.txt 2>stderr.debug.usa_richland_kruska_0.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealed CoCrNi_100.csv" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/Annealing_M2C_100.RRNG" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.ger_duesseldorf_li_0.nxs 1>stdout.debug.ger_duesseldorf_li_0.txt 2>stderr.debug.ger_duesseldorf_li_0.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/A718 GB R04_11350-V01.epos" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R04_11350-v01.rng.fig.txt" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.aus_sydney_felfer_0.nxs 1>stdout.debug.aus_sydney_felfer_0.txt 2>stderr.debug.aus_sydney_felfer_0.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/1748_Al.h5" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/1748_Al_range_.h5" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.ger_erlangen_monajem_0.nxs 1>stdout.debug.ger_erlangen_monajem_0.txt 2>stderr.debug.ger_erlangen_monajem_0.txt
dataconverter convert "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/R06_22236-v04.pos" "/home/kaiobach/Research/paper_paper_paper/joss_nomad_apt/bb_analysis/analysis/harvest_examples/production/default.analysis" "apm.oasis.specific.yaml" "eln_data_apm.yaml" --reader apm --nxdl NXapm --output=debug.usa_evanston_ren_0.nxs 1>stdout.debug.usa_evanston_ren_0.txt 2>stderr.usa_evanston_ren_0.txt
