
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-10T08:42:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "47402da7648cc49547ab3dc5a08e908f7a3cfb59",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
