# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _TopologyControlPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkFixTopologyCarveOutsidePython
else:
    import _itkFixTopologyCarveOutsidePython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.itkImagePython
import itk.itkRGBPixelPython
import itk.itkFixedArrayPython
import itk.pyBasePython
import itk.itkVectorPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.vnl_vector_refPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkMatrixPython
import itk.itkPointPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkIndexPython
import itk.ITKCommonBasePython
import itk.itkImageRegionPython
import itk.itkRGBAPixelPython
import itk.itkFixTopologyBasePython
import itk.itkImageToImageFilterAPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkPhasedArray3DSpecialCoordinatesImagePython
import itk.itkImageToImageFilterCommonPython

def itkFixTopologyCarveOutsideISS3_New():
    return itkFixTopologyCarveOutsideISS3.New()

class itkFixTopologyCarveOutsideISS3(itk.itkFixTopologyBasePython.itkFixTopologyBaseISS3):
    r"""Proxy of C++ itkFixTopologyCarveOutsideISS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkFixTopologyCarveOutsideISS3_Pointer"""
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideISS3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkFixTopologyCarveOutsideISS3_Pointer"""
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideISS3_Clone(self)
    __swig_destroy__ = _itkFixTopologyCarveOutsidePython.delete_itkFixTopologyCarveOutsideISS3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkFixTopologyCarveOutsideISS3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideISS3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkFixTopologyCarveOutsideISS3

        Create a new object of the class itkFixTopologyCarveOutsideISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkFixTopologyCarveOutsideISS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkFixTopologyCarveOutsideISS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkFixTopologyCarveOutsideISS3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkFixTopologyCarveOutsideISS3 in _itkFixTopologyCarveOutsidePython:
_itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideISS3_swigregister(itkFixTopologyCarveOutsideISS3)

def itkFixTopologyCarveOutsideIUC3_New():
    return itkFixTopologyCarveOutsideIUC3.New()

class itkFixTopologyCarveOutsideIUC3(itk.itkFixTopologyBasePython.itkFixTopologyBaseIUC3):
    r"""Proxy of C++ itkFixTopologyCarveOutsideIUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkFixTopologyCarveOutsideIUC3_Pointer"""
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUC3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkFixTopologyCarveOutsideIUC3_Pointer"""
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUC3_Clone(self)
    __swig_destroy__ = _itkFixTopologyCarveOutsidePython.delete_itkFixTopologyCarveOutsideIUC3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkFixTopologyCarveOutsideIUC3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUC3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkFixTopologyCarveOutsideIUC3

        Create a new object of the class itkFixTopologyCarveOutsideIUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkFixTopologyCarveOutsideIUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkFixTopologyCarveOutsideIUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkFixTopologyCarveOutsideIUC3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkFixTopologyCarveOutsideIUC3 in _itkFixTopologyCarveOutsidePython:
_itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUC3_swigregister(itkFixTopologyCarveOutsideIUC3)

def itkFixTopologyCarveOutsideIUS3_New():
    return itkFixTopologyCarveOutsideIUS3.New()

class itkFixTopologyCarveOutsideIUS3(itk.itkFixTopologyBasePython.itkFixTopologyBaseIUS3):
    r"""Proxy of C++ itkFixTopologyCarveOutsideIUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> itkFixTopologyCarveOutsideIUS3_Pointer"""
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUS3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> itkFixTopologyCarveOutsideIUS3_Pointer"""
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUS3_Clone(self)
    __swig_destroy__ = _itkFixTopologyCarveOutsidePython.delete_itkFixTopologyCarveOutsideIUS3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> itkFixTopologyCarveOutsideIUS3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUS3_cast(obj)

    def New(*args, **kargs):
        """New() -> itkFixTopologyCarveOutsideIUS3

        Create a new object of the class itkFixTopologyCarveOutsideIUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkFixTopologyCarveOutsideIUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkFixTopologyCarveOutsideIUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkFixTopologyCarveOutsideIUS3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkFixTopologyCarveOutsideIUS3 in _itkFixTopologyCarveOutsidePython:
_itkFixTopologyCarveOutsidePython.itkFixTopologyCarveOutsideIUS3_swigregister(itkFixTopologyCarveOutsideIUS3)

from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def fix_topology_carve_outside(*args: itkt.ImageLike,  mask_image: itkt.Image=..., radius: int=..., inside_value: int=...,**kwargs)-> itkt.ImageSourceReturn:
    """Functional interface for FixTopologyCarveOutside"""
    import itk

    kwarg_typehints = { 'mask_image':mask_image,'radius':radius,'inside_value':inside_value }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.FixTopologyCarveOutside.New(*args, **kwargs)

    return instance.__internal_call__()

def fix_topology_carve_outside_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.TopologyControl.FixTopologyCarveOutside
    fix_topology_carve_outside.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    fix_topology_carve_outside.__doc__ = filter_object.__doc__



