from ..util import SerializableResultT as SerializableResultT, create_analytics_message_packet as create_analytics_message_packet
from .base_client import BaseClient as BaseClient
from typing import Any

class AnalyticsFileWriter(BaseClient):
    def __init__(self, file_size_bytes: int = 500000) -> None: ...
    def publish_analytics(self, results: SerializableResultT, type: str, base_service: str, tag: Any = None, **kwargs): ...
    def stop(self) -> None: ...
