# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry_protos/snuba/v1alpha/request_common.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0sentry_protos/snuba/v1alpha/request_common.proto\x12\x1bsentry_protos.snuba.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n\x0bRequestMeta\x12\x17\n\x0forganization_id\x18\x01 \x01(\x04\x12\x15\n\rcogs_category\x18\x02 \x01(\t\x12\x10\n\x08referrer\x18\x03 \x01(\t\x12\x13\n\x0bproject_ids\x18\x04 \x03(\x04\x12\x33\n\x0fstart_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_timestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentry_protos.snuba.v1alpha.request_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMETA']._serialized_start=115
  _globals['_REQUESTMETA']._serialized_end=319
# @@protoc_insertion_point(module_scope)
