# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 1.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CovarianceOrbitType(str, Enum):
    """
    Type of parameters that can be used to describe the instantaneous covariance of an orbiting body. 
    """

    """
    allowed enum values
    """
    KEPLERIAN = 'KEPLERIAN'
    CIRCULAR = 'CIRCULAR'
    EQUINOCTIAL = 'EQUINOCTIAL'
    CARTESIAN = 'CARTESIAN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CovarianceOrbitType from a JSON string"""
        return cls(json.loads(json_str))


