from ..constants import TO_CLOUD_TOPIC_PREFIX as TO_CLOUD_TOPIC_PREFIX
from ..credentials import CLIENT_ID as CLIENT_ID, Certificates as Certificates, ENDPOINT as ENDPOINT
from .base_connection import BaseCloudConnection as BaseCloudConnection
from _typeshed import Incomplete
from typing import Callable

queue_messages: Incomplete

class IoTCoreConnection(BaseCloudConnection):
    AT_LEAST_ONCE: Incomplete
    AT_MOST_ONCE: Incomplete
    def __new__(cls): ...
    mqtt_connection: Incomplete
    topic: Incomplete
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def subscribe(self, topic: str, callback: Callable): ...
    def publish(self, message: str): ...
    def disconnect(self) -> None: ...
