class BaseCloudConnection:
    def __new__(cls): ...
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def publish(self, message: str): ...
    def disconnect(self) -> None: ...
