
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-09T20:22:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "870181cabb0a94e5dad5d80a1ba5a9b645062b1f",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
