
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-08T09:24:53+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "60bea1e3117837fae0b5506910b8006d348b5b81",
 "version": "0.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
