from _typeshed import Incomplete
from edgeiq._environment import CFG_DIR_ENV_VAR as CFG_DIR_ENV_VAR, SYSTEM_ID_ENV_VAR as SYSTEM_ID_ENV_VAR
from edgeiq._utils import JsonFile as JsonFile, gen_logger as gen_logger

APP_ROOT: Incomplete
MODELS_DIR: Incomplete
AAI_CONFIG_DIR: Incomplete
DEV_HOST_CONFIG_FILE_PATH: Incomplete
SYSTEM_ID_OPTIONS: Incomplete
LOGGER: Incomplete

def validate_system_id(system_id: str | None) -> str | None: ...

class AaiConfigFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def system_id(self) -> str | None: ...

def get_system_id() -> str: ...
def get_dev_host_credentials_file_path(system_id: str) -> str: ...

class DevHostCredentialsFile(JsonFile):
    def __init__(self, system_id: str) -> None: ...
    def get_refresh_token(self, user_pool_client_id) -> str | None: ...
    def get_id_token(self, user_pool_client_id) -> str | None: ...

def get_device_config_dir_path(system_id: str) -> str: ...
def get_device_config_file_path(system_id: str) -> str: ...

class DeviceConfigFile(JsonFile):
    def __init__(self, system_id: str) -> None: ...
    @property
    def refresh_token(self) -> str | None: ...
    @property
    def id_token(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...
    @property
    def device_uuid(self) -> str | None: ...

class DeviceConfigFileLegacy(JsonFile):
    def __init__(self) -> None: ...
    @property
    def system_id(self) -> str | None: ...
    @property
    def device_uuid(self) -> str | None: ...
