# Generated by Django 5.0.1 on 2024-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(help_text='Slug of the place', max_length=255),
        ),
    ]
