# Generated by Django 4.2.7 on 2024-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0007_role_prompt_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='tone_of_voice',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toneofvoice',
            name='name',
            field=models.TextField(),
        ),
    ]
