# Generated by Django 5.0.6 on 2024-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0013_agent_workflow_task_workflow_tool_is_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, to='prompt.tool'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='agents',
            field=models.ManyToManyField(blank=True, to='prompt.agent'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='prompt.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tools',
            field=models.ManyToManyField(blank=True, to='prompt.tool'),
        ),
    ]
