from .canvass import Canvass
from .client import Client
from .custom import Custom
from .customers import Customers
from .downloads import Downloads
from .file import File
from .installer import Installer
from .leads import Leads
from .menu import Menu
from .sales import Sales