{
 "title": "NodesDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result((cluster_read_io{cluster=~\".*\"}  and on() (absent(_{_=\"admin\"}) and absent(_{_=\"${__user.login}\"}))) or on() (cluster_read_io{cluster=\"${__user.login}\"}  unless on() (absent(_{_!=\"admin\"}) and absent(_{_=\"${user.login}\"}))))"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "query_result(device_size_total{cluster=~\"$cluster\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "snode_size_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_size_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_size_free{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_size_used{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_prov",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_size_prov{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_prov_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "snode_size_prov_util{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "snode_size_util{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "snode_write_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_write_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "snode_write_bytes_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_wite_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "snode_write_latency_ticks{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_write_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "snode_write_io{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "snode_write_io_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_write_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "snode_write_latency_ps{cluster=~\"$cluster\",snode=~\"$node\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "snode_read_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_read_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "snode_read_bytes_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_read_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "snode_read_latency_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_read_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "snode_read_io{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 40 },
   "targets": [
    {
     "expr": "snode_read_io_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_read_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "snode_read_latency_ticks{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "unmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "snode_unmap_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "snode_unmap_latency_ticks{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_bytes_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_unmap_bytes_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "snode_unmap_latency_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_io_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "snode_unmap_io_ps{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 55 },
   "targets": [
    {
     "expr": "snode_unmap_io{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snode_unmap_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_health_check",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 55 },
   "targets": [
    {
     "expr": "snode_health_check{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}