
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-10T10:52:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ce2a472dbb343e549c9cd4ef497b4f8ad647545",
 "version": "1.30.0.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
