
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-09T13:04:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f47e4e2d81471d661f7df8317b1ec1b4d564a95d",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
