# Generated by Django 5.0.9 on 2024-09-09 16:25

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0187_alter_device_vc_position'),
        ('extras', '0116_custom_link_button_color'),
        ('ipam', '0069_gfk_indexes'),
        ('netbox_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipam.vlan')),
            ],
            options={
                'ordering': ('site',),
            },
        ),
    ]