# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layer_model_pb/BiasAdd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1clayer_model_pb/BiasAdd.proto\x12\x0elayer_model_pb\":\n\nDnnBiasAdd\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\x12\x0f\n\x07\x66ilters\x18\x04 \x01(\tB+\n\x1b\x61ltair.layer.model.pb.graphB\x0c\x44nnBiasAddPbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'layer_model_pb.BiasAdd_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033altair.layer.model.pb.graphB\014DnnBiasAddPb'
  _DNNBIASADD._serialized_start=48
  _DNNBIASADD._serialized_end=106
# @@protoc_insertion_point(module_scope)
