# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layer_model_pb/Variable.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer_model_pb import Tensor_pb2 as layer__model__pb_dot_Tensor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlayer_model_pb/Variable.proto\x12\x0elayer_model_pb\x1a\x1blayer_model_pb/Tensor.proto\"D\n\x0b\x44nnVariable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x19.layer_model_pb.DnnTensorB,\n\x1b\x61ltair.layer.model.pb.graphB\rDnnVarialbePbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'layer_model_pb.Variable_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033altair.layer.model.pb.graphB\rDnnVarialbePb'
  _DNNVARIABLE._serialized_start=78
  _DNNVARIABLE._serialized_end=146
# @@protoc_insertion_point(module_scope)
