
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-12T09:43:52-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dcc0a2b0da44cb678cf06e74c22f09d7bacaf628",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
