# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 1.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.mean_orbit_ephemeris_request import MeanOrbitEphemerisRequest

class TestMeanOrbitEphemerisRequest(unittest.TestCase):
    """MeanOrbitEphemerisRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeanOrbitEphemerisRequest:
        """Test MeanOrbitEphemerisRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeanOrbitEphemerisRequest`
        """
        model = MeanOrbitEphemerisRequest()
        if include_optional:
            return MeanOrbitEphemerisRequest(
                mean_theory = 'DSST_6X0'
            )
        else:
            return MeanOrbitEphemerisRequest(
                mean_theory = 'DSST_6X0',
        )
        """

    def testMeanOrbitEphemerisRequest(self):
        """Test MeanOrbitEphemerisRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
