# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 1.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.battery_power_ephemeris_request import BatteryPowerEphemerisRequest

class TestBatteryPowerEphemerisRequest(unittest.TestCase):
    """BatteryPowerEphemerisRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatteryPowerEphemerisRequest:
        """Test BatteryPowerEphemerisRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatteryPowerEphemerisRequest`
        """
        model = BatteryPowerEphemerisRequest()
        if include_optional:
            return BatteryPowerEphemerisRequest(
            )
        else:
            return BatteryPowerEphemerisRequest(
        )
        """

    def testBatteryPowerEphemerisRequest(self):
        """Test BatteryPowerEphemerisRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
