# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dqeqanalytics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import dqdatetime_pb2 as dqdatetime__pb2
from . import dqanalytics_pb2 as dqanalytics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dqeqanalytics.proto',
  package='dqproto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x64qeqanalytics.proto\x12\x07\x64qproto\x1a\x10\x64qdatetime.proto\x1a\x11\x64qanalytics.proto\"\xf5\x02\n\x0c\x45qMktDataSet\x12!\n\nas_of_date\x18\x01 \x01(\x0b\x32\r.dqproto.Date\x12-\n\x0e\x64iscount_curve\x18\x02 \x01(\x0b\x32\x15.dqproto.IrYieldCurve\x12.\n\x0e\x64ividend_curve\x18\x03 \x01(\x0b\x32\x16.dqproto.DividendCurve\x12\x18\n\x10underlying_price\x18\x04 \x01(\x01\x12,\n\x08vol_surf\x18\x05 \x01(\x0b\x32\x1a.dqproto.VolatilitySurface\x12\x34\n\x15quanto_discount_curve\x18\x06 \x01(\x0b\x32\x15.dqproto.IrYieldCurve\x12\x35\n\x13quanto_fx_vol_curve\x18\x07 \x01(\x0b\x32\x18.dqproto.VolatilityCurve\x12\x1a\n\x12quanto_correlation\x18\x08 \x01(\x01\x12\x12\n\nunderlying\x18\t \x01(\t\"\xe1\x02\n\x0e\x45qRiskSettings\x12\x37\n\x11ir_curve_settings\x18\x01 \x01(\x0b\x32\x1c.dqproto.IrCurveRiskSettings\x12\x32\n\x0eprice_settings\x18\x02 \x01(\x0b\x32\x1a.dqproto.PriceRiskSettings\x12.\n\x0cvol_settings\x18\x03 \x01(\x0b\x32\x18.dqproto.VolRiskSettings\x12\x39\n\x12price_vol_settings\x18\x04 \x01(\x0b\x32\x1d.dqproto.PriceVolRiskSettings\x12\x32\n\x0etheta_settings\x18\x05 \x01(\x0b\x32\x1a.dqproto.ThetaRiskSettings\x12\x43\n\x17\x64ividend_curve_settings\x18\x06 \x01(\x0b\x32\".dqproto.DividendCurveRiskSettingsb\x06proto3'
  ,
  dependencies=[dqdatetime__pb2.DESCRIPTOR,dqanalytics__pb2.DESCRIPTOR,])




_EQMKTDATASET = _descriptor.Descriptor(
  name='EqMktDataSet',
  full_name='dqproto.EqMktDataSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='as_of_date', full_name='dqproto.EqMktDataSet.as_of_date', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='discount_curve', full_name='dqproto.EqMktDataSet.discount_curve', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dividend_curve', full_name='dqproto.EqMktDataSet.dividend_curve', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='underlying_price', full_name='dqproto.EqMktDataSet.underlying_price', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vol_surf', full_name='dqproto.EqMktDataSet.vol_surf', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quanto_discount_curve', full_name='dqproto.EqMktDataSet.quanto_discount_curve', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quanto_fx_vol_curve', full_name='dqproto.EqMktDataSet.quanto_fx_vol_curve', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quanto_correlation', full_name='dqproto.EqMktDataSet.quanto_correlation', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='underlying', full_name='dqproto.EqMktDataSet.underlying', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=443,
)


_EQRISKSETTINGS = _descriptor.Descriptor(
  name='EqRiskSettings',
  full_name='dqproto.EqRiskSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ir_curve_settings', full_name='dqproto.EqRiskSettings.ir_curve_settings', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_settings', full_name='dqproto.EqRiskSettings.price_settings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vol_settings', full_name='dqproto.EqRiskSettings.vol_settings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_vol_settings', full_name='dqproto.EqRiskSettings.price_vol_settings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='theta_settings', full_name='dqproto.EqRiskSettings.theta_settings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dividend_curve_settings', full_name='dqproto.EqRiskSettings.dividend_curve_settings', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=799,
)

_EQMKTDATASET.fields_by_name['as_of_date'].message_type = dqdatetime__pb2._DATE
_EQMKTDATASET.fields_by_name['discount_curve'].message_type = dqanalytics__pb2._IRYIELDCURVE
_EQMKTDATASET.fields_by_name['dividend_curve'].message_type = dqanalytics__pb2._DIVIDENDCURVE
_EQMKTDATASET.fields_by_name['vol_surf'].message_type = dqanalytics__pb2._VOLATILITYSURFACE
_EQMKTDATASET.fields_by_name['quanto_discount_curve'].message_type = dqanalytics__pb2._IRYIELDCURVE
_EQMKTDATASET.fields_by_name['quanto_fx_vol_curve'].message_type = dqanalytics__pb2._VOLATILITYCURVE
_EQRISKSETTINGS.fields_by_name['ir_curve_settings'].message_type = dqanalytics__pb2._IRCURVERISKSETTINGS
_EQRISKSETTINGS.fields_by_name['price_settings'].message_type = dqanalytics__pb2._PRICERISKSETTINGS
_EQRISKSETTINGS.fields_by_name['vol_settings'].message_type = dqanalytics__pb2._VOLRISKSETTINGS
_EQRISKSETTINGS.fields_by_name['price_vol_settings'].message_type = dqanalytics__pb2._PRICEVOLRISKSETTINGS
_EQRISKSETTINGS.fields_by_name['theta_settings'].message_type = dqanalytics__pb2._THETARISKSETTINGS
_EQRISKSETTINGS.fields_by_name['dividend_curve_settings'].message_type = dqanalytics__pb2._DIVIDENDCURVERISKSETTINGS
DESCRIPTOR.message_types_by_name['EqMktDataSet'] = _EQMKTDATASET
DESCRIPTOR.message_types_by_name['EqRiskSettings'] = _EQRISKSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EqMktDataSet = _reflection.GeneratedProtocolMessageType('EqMktDataSet', (_message.Message,), {
  'DESCRIPTOR' : _EQMKTDATASET,
  '__module__' : 'dqeqanalytics_pb2'
  # @@protoc_insertion_point(class_scope:dqproto.EqMktDataSet)
  })
_sym_db.RegisterMessage(EqMktDataSet)

EqRiskSettings = _reflection.GeneratedProtocolMessageType('EqRiskSettings', (_message.Message,), {
  'DESCRIPTOR' : _EQRISKSETTINGS,
  '__module__' : 'dqeqanalytics_pb2'
  # @@protoc_insertion_point(class_scope:dqproto.EqRiskSettings)
  })
_sym_db.RegisterMessage(EqRiskSettings)


# @@protoc_insertion_point(module_scope)
