# This file was auto-generated by Fern from our API Definition.

import typing

LipsyncTtsPageRequestSadtalkerSettingsPreprocess = typing.Union[
    typing.Literal["crop", "extcrop", "resize", "full", "extfull"], typing.Any
]
