from basicCGIserver import startCGIserver
from basicserverhttp import start_server_http
from socketServerClient.client import start_client_socket
from socketServerClient.server import start_socket_server