
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-10T17:09:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "89906f1eab4eeed1bfd64b2270a18eb61c9252cd",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
