# Generated by Django 4.2.1 on 2023-05-22 03:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('django_plotly_dash', '0002_add_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('specific_args', models.JSONField(blank=True, null=True)),
                ('instance_mode', models.PositiveSmallIntegerField(choices=[(0, 'Stateless'), (1, 'Per User')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('args', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoPlotlyDashPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('dash_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpwagtail.dashinstance')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='dashinstance',
            name='instance_builder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpwagtail.instancebuilder'),
        ),
        migrations.AddField(
            model_name='dashinstance',
            name='stateless_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_plotly_dash.statelessapp'),
        ),
    ]
