# Generated by Django 4.2.7 on 2023-11-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_gsheetsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
