# generated by scripts/generate_messages.py

from twnet_parser.pretty_print import PrettyPrint
from twnet_parser.packer import Unpacker

class ObjHammerHit(PrettyPrint):
    def __init__(
            self
    ) -> None:
        self.item_name: str = 'connless.hammer_hit'
        self.type_id: int = 16
        self.id: int = 0
        self.size: int = 2


    # first byte of data
    # has to be the first byte of the message payload
    # NOT the chunk header and NOT the message id
    def unpack(self, unpacker: Unpacker) -> bool:
        # common
        self.x = unpacker.get_int()
        self.y = unpacker.get_int()

        # hammer_hit
        return True

    def pack(self) -> bytes:
        return b''