# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.property_records200_response_inner_tax_assessments2019 import PropertyRecords200ResponseInnerTaxAssessments2019

class TestPropertyRecords200ResponseInnerTaxAssessments2019(unittest.TestCase):
    """PropertyRecords200ResponseInnerTaxAssessments2019 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyRecords200ResponseInnerTaxAssessments2019:
        """Test PropertyRecords200ResponseInnerTaxAssessments2019
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PropertyRecords200ResponseInnerTaxAssessments2019`
        """
        model = PropertyRecords200ResponseInnerTaxAssessments2019()
        if include_optional:
            return PropertyRecords200ResponseInnerTaxAssessments2019(
                value = 135430,
                land = 23450,
                improvements = 111980
            )
        else:
            return PropertyRecords200ResponseInnerTaxAssessments2019(
        )
        """

    def testPropertyRecords200ResponseInnerTaxAssessments2019(self):
        """Test PropertyRecords200ResponseInnerTaxAssessments2019"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
