# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.osculating_to_mean_configuration import OsculatingToMeanConfiguration

class TestOsculatingToMeanConfiguration(unittest.TestCase):
    """OsculatingToMeanConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOsculatingToMeanConfiguration(self):
        """Test OsculatingToMeanConfiguration"""
        # inst = OsculatingToMeanConfiguration()

if __name__ == '__main__':
    unittest.main()
