# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from ...core.serialization import FieldMetadata
import typing
from .credential_info import CredentialInfo
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CredentialReport(UniversalBaseModel):
    account_id: typing_extensions.Annotated[str, FieldMetadata(alias="accountId")]
    cluster_name: typing_extensions.Annotated[str, FieldMetadata(alias="clusterName")]
    credential: typing.Optional[CredentialInfo] = None
    errors: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
