import numpy as np
from abc import ABC
from edgeiq._production_client.util import SerializableResultT as SerializableResultT
from typing import Any

class BaseClient(ABC):
    def init(self) -> None: ...
    def publish_analytics(self, results: SerializableResultT, type: str, base_service: str, tag: Any = None, **kwargs): ...
    def publish_image(self, image: np.ndarray, tag: Any = None): ...
    def stop(self) -> None: ...
