# coding: utf-8

# flake8: noqa
"""
    Fideo API

    Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

    The version of the OpenAPI document: 1.0.4
    Contact: support@fideo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from fideo_api.models.alias import Alias
from fideo_api.models.demographics import Demographics
from fideo_api.models.economic import Economic
from fideo_api.models.education import Education
from fideo_api.models.education_date import EducationDate
from fideo_api.models.email import Email
from fideo_api.models.employment import Employment
from fideo_api.models.employment_date import EmploymentDate
from fideo_api.models.evidence import Evidence
from fideo_api.models.ip_country import IPCountry
from fideo_api.models.ip_address import IpAddress
from fideo_api.models.location import Location
from fideo_api.models.location_req import LocationReq
from fideo_api.models.location_type import LocationType
from fideo_api.models.multi_field_req import MultiFieldReq
from fideo_api.models.multi_field_req_with_options import MultiFieldReqWithOptions
from fideo_api.models.name import Name
from fideo_api.models.name_with_alias import NameWithAlias
from fideo_api.models.person_name_req import PersonNameReq
from fideo_api.models.phone import Phone
from fideo_api.models.photo import Photo
from fideo_api.models.score_details import ScoreDetails
from fideo_api.models.signals_post200_response import SignalsPost200Response
from fideo_api.models.signals_response_v0 import SignalsResponseV0
from fideo_api.models.signals_response_v20240424 import SignalsResponseV20240424
from fideo_api.models.social_profile_details import SocialProfileDetails
from fideo_api.models.social_profile_req import SocialProfileReq
from fideo_api.models.social_profile_urls import SocialProfileUrls
from fideo_api.models.verify_response import VerifyResponse
