# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequenz/api/common/v1/microgrid/components/battery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9frequenz/api/common/v1/microgrid/components/battery.proto\x12+frequenz.api.common.v1.microgrid.components\"Q\n\x07\x42\x61ttery\x12\x46\n\x04type\x18\x01 \x01(\x0e\x32\x38.frequenz.api.common.v1.microgrid.components.BatteryType*]\n\x0b\x42\x61tteryType\x12\x1c\n\x18\x42\x41TTERY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x42\x41TTERY_TYPE_LI_ION\x10\x01\x12\x17\n\x13\x42\x41TTERY_TYPE_NA_ION\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.common.v1.microgrid.components.battery_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATTERYTYPE._serialized_start=189
  _BATTERYTYPE._serialized_end=282
  _BATTERY._serialized_start=106
  _BATTERY._serialized_end=187
# @@protoc_insertion_point(module_scope)
