# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequenz/api/common/v1/microgrid/components/ev_charger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<frequenz/api/common/v1/microgrid/components/ev_charger.proto\x12+frequenz.api.common.v1.microgrid.components\"U\n\tEvCharger\x12H\n\x04type\x18\x01 \x01(\x0e\x32:.frequenz.api.common.v1.microgrid.components.EvChargerType*|\n\rEvChargerType\x12\x1f\n\x1b\x45V_CHARGER_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12\x45V_CHARGER_TYPE_AC\x10\x01\x12\x16\n\x12\x45V_CHARGER_TYPE_DC\x10\x02\x12\x1a\n\x16\x45V_CHARGER_TYPE_HYBRID\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.common.v1.microgrid.components.ev_charger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVCHARGERTYPE._serialized_start=196
  _EVCHARGERTYPE._serialized_end=320
  _EVCHARGER._serialized_start=109
  _EVCHARGER._serialized_end=194
# @@protoc_insertion_point(module_scope)
