# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequenz/api/common/v1/microgrid/components/transformer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=frequenz/api/common/v1/microgrid/components/transformer.proto\x12+frequenz.api.common.v1.microgrid.components\"8\n\x12VoltageTransformer\x12\x0f\n\x07primary\x18\x01 \x01(\x02\x12\x11\n\tsecondary\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.common.v1.microgrid.components.transformer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOLTAGETRANSFORMER._serialized_start=110
  _VOLTAGETRANSFORMER._serialized_end=166
# @@protoc_insertion_point(module_scope)
