from botoolkit.settings import (
    CONFIGURATION_DIRECTORY_PATH,
)


GUIDES_DIR_PATH = CONFIGURATION_DIRECTORY_PATH / 'guides'
GOOGLE_GUIDE_GIT_REPOSITORY_DIR_PATH = GUIDES_DIR_PATH / 'google_guides'
BARS_GUIDE_GIT_REPOSITORY_DIR_PATH = GUIDES_DIR_PATH / 'bars_guides'