import numpy as np
from ..util import SerializableResultT as SerializableResultT
from .base_client import BaseClient as BaseClient
from typing import Any, Optional

class ClientManager(BaseClient):
    def __init__(self) -> None: ...
    def add_client(self, client_class, *args) -> None: ...
    def publish_analytics(self, results: SerializableResultT, type: str, base_service: Optional[str], tag: Any = ..., **kwargs): ...
    def publish_image(self, image: np.ndarray, tag: Any = ...): ...
    def stop(self) -> None: ...
