# Generated by Django 4.2.7 on 2023-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_prompt_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='complete',
        ),
        migrations.AddField(
            model_name='prompt',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
