# Generated by Django 4.2.7 on 2023-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0005_remove_prompt_complete_prompt_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
