# Generated by Django 5.0.6 on 2024-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0011_tool_agent_task_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_output',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
