# Generated by Django 5.0.6 on 2024-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0012_task_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='workflow',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='workflow',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
