# Generated by Django 5.0.6 on 2024-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0018_remove_prompt_data_remove_prompt_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
