
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-08T06:33:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "685e2c6118f165d52bade47ab1c696ec9e0945a4",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
