from typing import Any, Dict, List, Optional

class RustAism:
    def __init__(
        self, *, api_key: Optional[str] = None, debug: bool = False
    ) -> None: ...
    def give(self, data: str) -> "RustInstance": ...
    def feed(self, rows: List[str]) -> "RustInstance": ...

class RustInstance:
    def give(self, data: str) -> "RustInstance": ...
    def feed(self, rows: List[str]) -> "RustInstance": ...
    def instruct(self, instruction: str) -> str: ...
    def translate(self, language: str) -> str: ...
    def is_sensitive(self) -> bool: ...
    def mentioned(self, keyword: str) -> bool: ...
    def matches(self, keyword: str) -> bool: ...
    def fill_dict(self, d: str) -> Dict[str, Any]: ...
    def summarize(self) -> str: ...
    def _conv(
        self,
        msgs: List[Dict[str, str]],
    ) -> str: ...
