from . import (
    analysis as analysis,
    bit_reader as bit_reader,
    core as core,
    disassembler as disassembler,
    error_handling as error_handling,
    linker as linker,
    object as object,
    support as support,
    target as target,
    target_machine as target_machine,
    utils as utils
)


class PyBinaryObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PyBinaryObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymAttributeObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymAttributeObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymBasicBlockObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymBasicBlockObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymBuilderObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymBuilderObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymContextObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymContextObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymDiagnosticInfoObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymDiagnosticInfoObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymDisasmContextObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymDisasmContextObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymIntrinsicObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymIntrinsicObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymMemoryBufferObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymMemoryBufferObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymMetadataEntriesObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymMetadataEntriesObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymMetadataObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymMetadataObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymModuleFlagEntriesObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymModuleFlagEntriesObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymModuleObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymModuleObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymModuleProviderObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymModuleProviderObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymNamedMDNodeObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymNamedMDNodeObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymOperandBundleObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymOperandBundleObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymPassManagerBaseObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymPassManagerBaseObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymTargetDataObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymTargetDataObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymTargetLibraryInfoObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymTargetLibraryInfoObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymTargetMachineObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymTargetMachineObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymTargetMachineOptionsObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymTargetMachineOptionsObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymTargetObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymTargetObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymTypeObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymTypeObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymUseObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymUseObject, /) -> bool: ...

    def __hash__(self) -> int: ...

class PymValueObject:
    """The base class."""

    def __bool__(self) -> bool: ...

    def __eq__(self, arg: PymValueObject, /) -> bool: ...

    def __hash__(self) -> int: ...
