# coding: utf-8

"""
    RentCast API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentcast_client.models.market_statistics200_response_rental_data_history202312 import MarketStatistics200ResponseRentalDataHistory202312

class TestMarketStatistics200ResponseRentalDataHistory202312(unittest.TestCase):
    """MarketStatistics200ResponseRentalDataHistory202312 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketStatistics200ResponseRentalDataHistory202312:
        """Test MarketStatistics200ResponseRentalDataHistory202312
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketStatistics200ResponseRentalDataHistory202312`
        """
        model = MarketStatistics200ResponseRentalDataHistory202312()
        if include_optional:
            return MarketStatistics200ResponseRentalDataHistory202312(
                average_rent = 1362,
                min_rent = 575,
                max_rent = 2800,
                total_listings = 87,
                data_by_bedrooms = [
                    rentcast_client.models.market_statistics_200_response_rental_data_history_2023_12_data_by_bedrooms_inner.market_statistics_200_response_rentalData_history_2023_12_dataByBedrooms_inner(
                        bedrooms = 1, 
                        average_rent = 934, 
                        min_rent = 575, 
                        max_rent = 1610, 
                        total_listings = 7, )
                    ]
            )
        else:
            return MarketStatistics200ResponseRentalDataHistory202312(
        )
        """

    def testMarketStatistics200ResponseRentalDataHistory202312(self):
        """Test MarketStatistics200ResponseRentalDataHistory202312"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
