
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-09T16:36:59+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a411061271f8f4ca36b6b1c1bb9ee43637263dc",
 "version": "1.8.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
